name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer -v android debug
        buildozer_version: master

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          bin/*.apk
